TYPE analog_input_8channel_udt :
STRUCT
	{attribute 'symbol' := 'read'}
	position1: REAL;
	{attribute 'symbol' := 'read'}
	position1_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position2: REAL;
	{attribute 'symbol' := 'read'}
	position2_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position3: REAL;
	{attribute 'symbol' := 'read'}
	position3_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position4: REAL;
	{attribute 'symbol' := 'read'}
	position4_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position5: REAL;
	{attribute 'symbol' := 'read'}
	position5_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position6: REAL;
	{attribute 'symbol' := 'read'}
	position6_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position7: REAL;
	{attribute 'symbol' := 'read'}
	position7_fault: BOOL;
	{attribute 'symbol' := 'read'}
	position8: REAL;
	{attribute 'symbol' := 'read'}
	position8_fault: BOOL;
END_STRUCT
END_TYPE
